"""add-qa

Revision ID: 694890d2fe42
Revises: bc5f7d589ae8
Create Date: 2023-05-06 13:36:03.220695

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '694890d2fe42'
down_revision = 'bc5f7d589ae8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qa',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True, comment='最后修改时间'),
    sa.Column('uuid', sa.String(length=64), nullable=False, comment='QA的uuid'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='QA的标题'),
    sa.Column('is_default', sa.Boolean(), nullable=False, comment='是否是默认，False表示不是，True表示是。默认False。'),
    sa.Column('enabled', sa.Enum('enabled', 'disabled'), nullable=False, comment='QA的启用状态，enabled表示启用，disabled表示已禁用'),
    sa.Column('desc', sa.String(length=255), nullable=False, comment='QA的描述信息'),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.drop_column('user', 'type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('type', mysql.CHAR(length=64), nullable=True))
    op.drop_table('qa')
    # ### end Alembic commands ###
