"""jjtest-set-model-all-true

Revision ID: 94e51c3736f9
Revises: bc5f7d589ae8
Create Date: 2023-05-09 18:26:40.208445

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '94e51c3736f9'
down_revision = 'bc5f7d589ae8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jjtest', 'age',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_comment='age')
    op.alter_column('jjtest', 'desc',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False,
               existing_comment='描述信息')
    op.alter_column('jjtest', 'email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False,
               existing_comment='邮箱')
    op.alter_column('jjtest', 'sex',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_comment='是否为男')
    op.alter_column('jjtest', 'time',
               existing_type=mysql.TIMESTAMP(),
               nullable=False,
               existing_comment='时间')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jjtest', 'time',
               existing_type=mysql.TIMESTAMP(),
               nullable=True,
               existing_comment='时间')
    op.alter_column('jjtest', 'sex',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_comment='是否为男')
    op.alter_column('jjtest', 'email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True,
               existing_comment='邮箱')
    op.alter_column('jjtest', 'desc',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True,
               existing_comment='描述信息')
    op.alter_column('jjtest', 'age',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_comment='age')
    # ### end Alembic commands ###
