"""init

Revision ID: bc5f7d589ae8
Revises: 
Create Date: 2021-01-28 09:58:54.368732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc5f7d589ae8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('desktop',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True, comment='最后修改时间'),
    sa.Column('uuid', sa.String(length=64), nullable=False, comment='自定义桌面uuid'),
    sa.Column('vm_uuid', sa.String(length=64), nullable=False, comment='虚拟化平台上虚机的uuid'),
    sa.Column('display_name', sa.String(length=255), nullable=False, comment='桌面的显示名称'),
    sa.Column('is_attached_gpu', sa.Boolean(), nullable=False, comment='桌面是否挂载gpu'),
    sa.Column('is_default', sa.Boolean(), nullable=False, comment='是否是默认桌面，False表示不是，True表示是。默认False。'),
    sa.Column('enabled', sa.Enum('enabled', 'disabled'), nullable=False, comment='桌面的启用状态，enabled表示启用，disabled表示桌面已禁用'),
    sa.Column('node_uuid', sa.String(length=64), nullable=False, comment='物理机uuid'),
    sa.Column('node_name', sa.String(length=255), nullable=False, comment='物理机名称'),
    sa.Column('desc', sa.String(length=255), nullable=False, comment='桌面的描述信息'),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_desktop_vm_uuid'), 'desktop', ['vm_uuid'], unique=True)
    op.create_table('user',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True, comment='最后修改时间'),
    sa.Column('uuid', sa.String(length=64), nullable=False, comment='uuid'),
    sa.Column('login_name', sa.String(length=64), nullable=False, comment='登录名'),
    sa.Column('password', sa.String(length=255), nullable=False, comment='密码'),
    sa.Column('display_name', sa.String(length=255), nullable=False, comment='姓名'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='邮箱'),
    sa.Column('phone', sa.String(length=255), nullable=False, comment='电话'),
    sa.Column('enabled', sa.Enum('enabled', 'disabled'), nullable=False, comment='用户的启用状态，enabled表示启用，disabled表示禁用'),
    sa.Column('desc', sa.String(length=255), nullable=False, comment='描述信息'),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('login_name')
    )
    op.create_index(op.f('ix_user_display_name'), 'user', ['display_name'], unique=False)

    op.execute("insert into user(uuid,login_name,display_name,password,email,phone,user.desc,created_at,updated_at) values  "
               "('default_uuid', 'admin', 'admin', '$2b$12$LMvuoGYhCCBCswKAA1WpKeTIl3Bh94qsGsX4se6wu10pWfnbaZHuu', "
               "'', '', '', now(), now())")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_display_name'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_desktop_vm_uuid'), table_name='desktop')
    op.drop_table('desktop')
    # ### end Alembic commands ###
